/******************************************************************************/
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   main.cpp                                           :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: masoares <masoares@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2024/09/29 17:04:39 by marvin            #+#    #+#             */
/*   Updated: 2024/10/01 11:03:29 by masoares         ###   ########.fr       */
/*                                                                            */
/******************************************************************************/

#include "A.hpp"
#include "B.hpp"
#include "C.hpp"

int main ( void )
{
	Base *lala;

    srand(time(NULL));

    lala = generate();
    identify(lala);
    std::cout<< std::endl;
    identify(*lala);
}

/*The reason you need to call srand(time(NULL)); before using rand() is to seed the random number generator with a unique starting point
    rand():
        The rand() function generates a sequence of pseudo-random numbers.
        It uses a mathematical algorithm to generate numbers, which means the sequence is deterministic: 
    if the starting point (or seed) is the same, the sequence of numbers generated will also be the same.

    srand(seed):
        The srand() function sets the starting seed value for the rand() function.
        If you don't call srand(), the rand() function will use a default seed value (usually 1 in many implementations).

    Using srand(time(NULL)); is a common technique to set the seed value based on the current time. Here's what each part does:

        time(NULL):
            Returns the current time in seconds since the Unix epoch (January 1, 1970).
        srand(time(NULL));:
            Initializes the random number generator with this changing seed value, making the sequence of numbers generated by rand() different every time */